/* AUTO-GENERATED by scripts/update-signals.mjs — do not edit by hand. */
window.LIVE_SIGNALS = {
  "generatedAt": "2026-06-17T23:39:19.955Z",
  "model": "gpt-4o",
  "mode": "live",
  "stocks": {
    "ORCL": {
      "signals": {
        "rpo": {
          "value": "$638B",
          "delta": "+$85B QoQ",
          "trend": "up",
          "stance": "bull",
          "raw": 90,
          "note": "Record backlog provides substantial revenue visibility."
        },
        "oci": {
          "value": "+93% YoY",
          "delta": "+29pp QoQ",
          "trend": "up",
          "stance": "bull",
          "raw": 95,
          "note": "OCI revenue surge confirms strong AI cloud demand."
        },
        "capex": {
          "value": "$55.7B",
          "delta": "+$15.8B YoY",
          "trend": "up",
          "stance": "bear",
          "raw": 85,
          "note": "Elevated capex raises concerns about funding and cash flow."
        },
        "fcf": {
          "value": "-$23.7B",
          "delta": "-$24.1B YoY",
          "trend": "down",
          "stance": "bear",
          "raw": 10,
          "note": "Negative free cash flow intensifies funding worries."
        },
        "debt": {
          "value": "$40B",
          "delta": "+$40B YoY",
          "trend": "up",
          "stance": "bear",
          "raw": 80,
          "note": "Significant debt issuance to fund AI expansion."
        }
      },
      "price": 183.53,
      "changePct": -2.54,
      "asOf": "2026-06-17",
      "summary": "Oracle's strong cloud growth is overshadowed by significant capex and negative free cash flow, raising funding concerns.",
      "sources": [
        "https://www.ebc.com/forex/oracle-stock-orcl-earnings-q4-fy2026-ai-capex"
      ]
    },
    "MSFT": {
      "signals": {
        "azure": {
          "value": "+39% YoY",
          "delta": "+5pp QoQ",
          "trend": "up",
          "stance": "bull",
          "raw": 90,
          "note": "Azure's growth exceeds expectations, driven by AI demand."
        },
        "airunrate": {
          "value": "$37B",
          "delta": "+$2B QoQ",
          "trend": "up",
          "stance": "bull",
          "raw": 85,
          "note": "AI business annual run-rate surpasses $37B, indicating strong adoption."
        },
        "copilot": {
          "value": "20M seats",
          "delta": "+5M QoQ",
          "trend": "up",
          "stance": "bull",
          "raw": 80,
          "note": "Microsoft 365 Copilot reaches 20M paid seats, showcasing rapid growth."
        },
        "capex": {
          "value": "$31.9B",
          "delta": "+$2.0B QoQ",
          "trend": "up",
          "stance": "bear",
          "raw": 75,
          "note": "Accelerating capex may pressure near-term margins."
        },
        "fcf": {
          "value": "$72.9B",
          "delta": "+$1.3B YoY",
          "trend": "up",
          "stance": "bull",
          "raw": 85,
          "note": "Strong free cash flow supports ongoing investments."
        },
        "gm": {
          "value": "68.31%",
          "delta": "-0.28pp YoY",
          "trend": "down",
          "stance": "neutral",
          "raw": 70,
          "note": "Slight gross margin decline due to increased AI infrastructure costs."
        }
      },
      "price": 378.91,
      "changePct": -3.8,
      "asOf": "2026-06-17",
      "summary": "Microsoft's robust cloud and AI growth is tempered by rising capex and margin pressures.",
      "sources": [
        "https://www.marketbeat.com/instant-alerts/microsoft-nasdaqmsft-issues-earnings-results-2026-04-29/"
      ]
    },
    "HOOD": {
      "signals": {
        "deposits": {
          "value": "$18.4B",
          "delta": "+$2.3B QoQ",
          "trend": "up",
          "stance": "bull",
          "raw": 85,
          "note": "Net deposits indicate robust user growth and engagement."
        },
        "options": {
          "value": "2.1M/day",
          "delta": "+0.3M QoQ",
          "trend": "up",
          "stance": "bull",
          "raw": 80,
          "note": "Increased options volume reflects heightened trading activity."
        },
        "crypto": {
          "value": "$52B",
          "delta": "+$8B QoQ",
          "trend": "up",
          "stance": "bull",
          "raw": 75,
          "note": "Crypto trading volume rebounds, contributing to revenue growth."
        },
        "gold": {
          "value": "4.6M",
          "delta": "+0.5M QoQ",
          "trend": "up",
          "stance": "bull",
          "raw": 70,
          "note": "Growth in Gold subscribers enhances recurring revenue streams."
        },
        "arpu": {
          "value": "$168",
          "delta": "+$12 QoQ",
          "trend": "up",
          "stance": "bull",
          "raw": 80,
          "note": "Rising ARPU indicates improved monetization per user."
        }
      },
      "price": 105.2,
      "changePct": 8.75,
      "asOf": "2026-06-17",
      "summary": "Robinhood's strong growth in net deposits and options volume underscores its expanding user base and engagement.",
      "sources": []
    },
    "NKE": {
      "signals": {
        "gm": {
          "value": "42.1%",
          "delta": "-1.5pp YoY",
          "trend": "down",
          "stance": "bear",
          "raw": 40,
          "note": "Gross margin decline driven by increased promotions and markdowns."
        },
        "inv": {
          "value": "+6% YoY",
          "delta": "-4pp QoQ",
          "trend": "down",
          "stance": "bear",
          "raw": 30,
          "note": "Elevated inventory levels necessitate further markdowns."
        },
        "china": {
          "value": "-9% YoY",
          "delta": "-3pp QoQ",
          "trend": "down",
          "stance": "bear",
          "raw": 25,
          "note": "Declining sales in Greater China impact overall growth."
        },
        "dtc": {
          "value": "-12% YoY",
          "delta": "-5pp QoQ",
          "trend": "down",
          "stance": "bear",
          "raw": 20,
          "note": "Pullback in DTC sales affects margin recovery efforts."
        }
      },
      "price": 44.19,
      "changePct": -1.89,
      "asOf": "2026-06-17",
      "summary": "Nike faces margin pressures due to high inventory levels and markdowns, with declining China sales adding to challenges.",
      "sources": []
    },
    "GEV": {
      "signals": {
        "backlog": {
          "value": "$128B",
          "delta": "+$10B QoQ",
          "trend": "up",
          "stance": "bull",
          "raw": 90,
          "note": "Record backlog provides multi-year revenue visibility."
        },
        "turbine": {
          "value": "Sold to 2028",
          "delta": "+1 year QoQ",
          "trend": "up",
          "stance": "bull",
          "raw": 85,
          "note": "Gas turbine slots sold out, indicating strong demand."
        },
        "gw": {
          "value": "55 GW",
          "delta": "+5 GW QoQ",
          "trend": "up",
          "stance": "bull",
          "raw": 80,
          "note": "Contracted gigawatts under power highlight robust order book."
        },
        "dcpower": {
          "value": "$14B",
          "delta": "+$2B QoQ",
          "trend": "up",
          "stance": "bull",
          "raw": 75,
          "note": "Datacenter power orders reflect growing AI infrastructure needs."
        },
        "fcf": {
          "value": "9.2%",
          "delta": "+1.0pp QoQ",
          "trend": "up",
          "stance": "bull",
          "raw": 80,
          "note": "Improving free cash flow margin supports financial health."
        }
      },
      "price": 1048.86,
      "changePct": 6.82,
      "asOf": "2026-06-17",
      "summary": "GE Vernova's substantial backlog and contracted power orders position it well for sustained growth in the electrification sector.",
      "sources": []
    }
  }
};
