/* AUTO-GENERATED by scripts/update-signals.mjs — do not edit by hand.
   Stub: no live data yet. The scheduled researcher overwrites this file with
   window.LIVE_SIGNALS = { generatedAt, model, mode, stocks: {...} }.
   Until then, the terminal runs on the curated reference data in data.js. */
window.LIVE_SIGNALS = null;
