/* AUTO-GENERATED by scripts/update-signals.mjs — do not edit by hand. */
window.LIVE_SIGNALS = {
  "generatedAt": "2026-06-20T04:52:20.428Z",
  "model": "gpt-5.5",
  "mode": "live",
  "stocks": {
    "MSFT": {
      "signals": {
        "azure": {
          "value": "+40% YoY",
          "delta": "+1 pp QoQ",
          "trend": "up",
          "stance": "bull",
          "raw": 82,
          "note": "Azure and other cloud services grew 40%, up from 39% last quarter.",
          "hist": [
            40
          ]
        },
        "airunrate": {
          "value": "$37B ARR",
          "delta": "+123% YoY",
          "trend": "up",
          "stance": "bull",
          "raw": 86,
          "note": "AI business surpassed $37B ARR, still scaling much faster than core cloud.",
          "hist": [
            37
          ]
        },
        "copilot": {
          "value": ">20M seats",
          "delta": "+5M QoQ",
          "trend": "up",
          "stance": "neutral",
          "raw": 56,
          "note": "Paid M365 Copilot seats rose from 15M, but attach is still only about 4% of 450M users.",
          "hist": [
            20
          ],
          "valueFrom": "20M seats",
          "stanceFrom": "bull"
        },
        "capex": {
          "value": "37% of rev",
          "delta": "+13 pp YoY",
          "trend": "up",
          "stance": "bear",
          "raw": 28,
          "note": "Q3 PP&E additions were $30.9B versus $82.9B revenue; CY26 capex guided near $190B.",
          "hist": [
            37
          ],
          "valueFrom": "37.3%"
        },
        "fcf": {
          "value": "19% margin",
          "delta": "-10 pp YoY",
          "trend": "down",
          "stance": "bear",
          "raw": 38,
          "note": "OCF less PP&E was $15.8B, strong in dollars but sharply compressed by AI buildout.",
          "hist": [
            19
          ],
          "valueFrom": "19.1%"
        },
        "gm": {
          "value": "66% cloud GM",
          "delta": "-1 pp QoQ",
          "trend": "down",
          "stance": "bear",
          "raw": 40,
          "note": "Microsoft Cloud GM fell to 66% as AI infrastructure and Copilot usage diluted margin.",
          "hist": [
            66
          ],
          "valueFrom": "66%"
        },
        "power": {
          "value": "40 GW PPA",
          "delta": "",
          "trend": "up",
          "stance": "bull",
          "raw": 75,
          "note": "Microsoft says it contracted 40GW renewable power, with 19GW online, supporting future capacity.",
          "hist": [
            40
          ],
          "valueFrom": "1GW online"
        },
        "rs": {
          "value": "-288 bps",
          "delta": "",
          "trend": "down",
          "stance": "bear",
          "raw": 35,
          "note": "Latest session MSFT lagged XLK by about 288 bps, showing no sector leadership.",
          "hist": [
            -288
          ],
          "valueFrom": "-39pp YTD"
        },
        "iv": {
          "value": "IVR 33%",
          "delta": "",
          "trend": "flat",
          "stance": "neutral",
          "raw": 50,
          "note": "Recent options screens showed MSFT IV near 30% and IV rank around 33%, not pricing shock.",
          "hist": [
            33
          ],
          "valueFrom": "IVR 52 · flat"
        },
        "insider": {
          "value": "-$7.7M 90d",
          "delta": "",
          "trend": "down",
          "stance": "neutral",
          "raw": 48,
          "note": "Last 90 days show modest net insider selling and no purchases; not thesis-changing.",
          "hist": [
            7.7
          ],
          "valueFrom": "$8.6M"
        },
        "rev": {
          "value": "$17.10 FY26",
          "delta": "+0.51",
          "trend": "up",
          "stance": "bull",
          "raw": 70,
          "note": "Consensus FY26 EPS sits above the most recent consensus snapshot after the Q3 beat.",
          "hist": [
            17.1
          ],
          "valueFrom": "FY26 $17.10"
        },
        "x_sent": {
          "value": "Mixed 52%",
          "delta": "",
          "trend": "flat",
          "stance": "neutral",
          "raw": 52,
          "note": "Recent social reads show split AI optimism versus capex/stock-lag frustration.",
          "hist": [
            52
          ],
          "valueFrom": "Mixed"
        },
        "reddit_sent": {
          "value": "Bearish 28%",
          "delta": "",
          "trend": "down",
          "stance": "bear",
          "raw": 28,
          "note": "Recent Reddit threads skew frustrated on underperformance, despite dip-buying comments.",
          "hist": [
            28
          ]
        },
        "pro_sent": {
          "value": "Strong Buy",
          "delta": "",
          "trend": "up",
          "stance": "bull",
          "raw": 82,
          "note": "Sell-side remains constructive, with 56-analyst consensus Strong Buy and ~$561 target.",
          "hist": []
        }
      },
      "price": 379.4,
      "changePct": 0.12,
      "asOf": "2026-06-19",
      "earnings": "2026-07-29",
      "summary": "Azure and AI monetization remain strong, but the tape is penalizing rising capex intensity, FCF compression and weak relative performance.",
      "sources": [
        "https://www.microsoft.com/en-us/investor/earnings/fy-2026-q3/press-release-webcast",
        "https://www.microsoft.com/en-us/investor/events/fy-2026/earnings-fy-2026-q3",
        "https://www.stockanalysis.com/stocks/msft/forecast/",
        "https://www.insiderscreener.com/en/company/microsoft-corp"
      ],
      "news": [
        {
          "title": "Microsoft makes Copilot Cowork open to everyone, and wants to help you tackle even the trickiest work tasks",
          "url": "https://www.techradar.com/pro/microsoft-makes-copilot-cowork-open-to-everyone-and-wants-to-help-you-tackle-even-the-trickiest-work-tasks",
          "source": "TechRadar",
          "isNew": true
        },
        {
          "title": "Microsoft weighs DeepSeek for Copilot Cowork",
          "url": "https://www.axios.com/2026/06/16/microsoft-copilot-cowork-tokenmaxxing-cowork",
          "source": "Axios",
          "isNew": false
        },
        {
          "title": "Microsoft sued over performance of Azure business",
          "url": "https://www.itpro.com/cloud/cloud-management/microsoft-sued-over-performance-of-azure-business",
          "source": "ITPro",
          "isNew": false
        }
      ],
      "priceHist": [
        379.4
      ]
    },
    "GEV": {
      "signals": {
        "backlog": {
          "value": "$163.3B",
          "delta": "+13.0B QoQ",
          "trend": "up",
          "stance": "bull",
          "raw": 95,
          "note": "Total RPO hit a record $163.3B in Q1, up sharply sequentially with Power and Electrification strength.",
          "hist": [
            163.3
          ],
          "valueFrom": "$163B"
        },
        "turbine": {
          "value": "56 GW slots",
          "delta": "+13 GW QoQ",
          "trend": "up",
          "stance": "bull",
          "raw": 93,
          "note": "Gas slot reservations rose to 56 GW from 43 GW, reinforcing scarce turbine capacity and pricing power.",
          "hist": [
            56
          ],
          "valueFrom": "Into 2031"
        },
        "gw": {
          "value": "100 GW",
          "delta": "+17 GW QoQ",
          "trend": "up",
          "stance": "bull",
          "raw": 95,
          "note": "Gas Power backlog plus slot reservations reached 100 GW, with management targeting at least 110 GW by year-end.",
          "hist": [
            100
          ]
        },
        "dcpower": {
          "value": "$2.4B",
          "delta": ">FY25 total",
          "trend": "up",
          "stance": "bull",
          "raw": 90,
          "note": "Q1 Electrification equipment orders supporting data centers exceeded the full-year 2025 level.",
          "hist": [
            2.4
          ],
          "valueFrom": "Q1 $2.4B"
        },
        "fcf": {
          "value": "51.3%",
          "delta": "+3916 bps YoY",
          "trend": "up",
          "stance": "bull",
          "raw": 96,
          "note": "Q1 FCF of $4.79B on $9.34B revenue drove a 51.3% FCF margin, helped by working capital.",
          "hist": [
            51.3
          ]
        },
        "grid": {
          "value": "$38.6B",
          "delta": "+75% YoY",
          "trend": "up",
          "stance": "bull",
          "raw": 92,
          "note": "Electrification equipment backlog rose $16.6B YoY to $38.6B, including Prolec GE and grid demand.",
          "hist": [
            38.6
          ]
        },
        "rs": {
          "value": "+107% YTD",
          "delta": "",
          "trend": "up",
          "stance": "bull",
          "raw": 88,
          "note": "GEV’s 2026 tape has materially outperformed industrials, keeping the stock in a leadership lane.",
          "hist": [
            107
          ],
          "valueFrom": "+51.5pp YTD"
        },
        "iv": {
          "value": "IV56/IVR49",
          "delta": "",
          "trend": "flat",
          "stance": "neutral",
          "raw": 49,
          "note": "Recent options screens showed 56% IV, 49% IV rank and elevated put volume, signaling two-way positioning risk.",
          "hist": [
            56
          ],
          "valueFrom": "IVR48 P/C1.29"
        },
        "insider": {
          "value": "$7.04M sold",
          "delta": "0 buys",
          "trend": "up",
          "stance": "bear",
          "raw": 62,
          "note": "Q2 insider activity shows notable open-market selling and no offsetting insider purchases.",
          "hist": [
            7.04
          ],
          "valueFrom": "-$7.0M 90d",
          "stanceFrom": "neutral"
        },
        "rev": {
          "value": "FY26 +8.3%",
          "delta": "+$1.08/90d",
          "trend": "up",
          "stance": "bull",
          "raw": 80,
          "note": "Consensus FY26 EPS estimates moved higher over the prior 90 days, consistent with raised guidance.",
          "hist": [
            26
          ],
          "valueFrom": "16 up/0 down"
        },
        "x_sent": {
          "value": "Bullish 70%",
          "delta": "",
          "trend": "up",
          "stance": "bull",
          "raw": 70,
          "note": "Recent X chatter frames GEV as an AI-grid leader, though some posts flag valuation and pullback risk.",
          "hist": [
            70
          ],
          "valueFrom": "Mixed-bull"
        },
        "reddit_sent": {
          "value": "Mixed-bull",
          "delta": "",
          "trend": "flat",
          "stance": "bull",
          "raw": 60,
          "note": "Recent Reddit posts debate chasing the stock, but the AI power and backlog thesis remains prominent.",
          "hist": [],
          "valueFrom": "Mixed",
          "stanceFrom": "neutral"
        },
        "pro_sent": {
          "value": "Buy $1.21k",
          "delta": "",
          "trend": "up",
          "stance": "bull",
          "raw": 82,
          "note": "Jefferies reiterated Buy and called GEV a top 2026 power/utilities franchise pick with a $1,210 target.",
          "hist": [
            1.21
          ],
          "valueFrom": "Buy +10%"
        }
      },
      "price": 1109.73,
      "changePct": 5.8,
      "asOf": "2026-06-18",
      "earnings": "2026-07-22",
      "summary": "GE Vernova still screens bullish on record backlog, turbine scarcity and cash conversion, offset by rich positioning and insider sales.",
      "sources": [
        "https://www.sec.gov/Archives/edgar/data/1996810/000199681026000063/gevpressrelease1q26.htm",
        "https://www.gevernova.com/sites/default/files/gev_webcast_presentation_04222026.pdf",
        "https://www.marketbeat.com/stocks/NYSE/GEV/insider-trades/",
        "https://www.investing.com/news/stock-market-news/jefferies-top-power--utilities-stock-pick-for-2026-93CH-4742877"
      ],
      "news": [
        {
          "title": "GE Vernova Hitachi and Velan expand collaboration to support BWRX-300 small modular reactor deployment in Europe",
          "url": "https://www.gevernova.com/news/media-hub",
          "source": "GE Vernova",
          "isNew": true
        },
        {
          "title": "Jefferies’ top power & utilities stock pick for 2026",
          "url": "https://www.investing.com/news/stock-market-news/jefferies-top-power--utilities-stock-pick-for-2026-93CH-4742877",
          "source": "Investing.com",
          "isNew": true
        },
        {
          "title": "GE Vernova Introduces GridOS for Transmission and New AI Whitepapers at Orchestrate 2026",
          "url": "https://www.gevernova.com/news/media-hub",
          "source": "GE Vernova",
          "isNew": true
        }
      ],
      "priceHist": [
        1109.73
      ]
    }
  }
};
